### ISSUE TITLE
JS ref. impl TODO:

### ISSUE THREAD

**Issue by ApricotLace** [fhir-schema/fhir-schema#9]
- [ ] Tests
- [ ] Converter SD -> FHIRSchema
- [ ] JS impl.
  - [ ] Terminology validation (ValueSet bindings only)
  - [ ] FHIRPath
  - [ ] Extension validation (dispatch on URL)
  - [ ] Primitives validation
  - [ ] Arrays checks (arrities, shape, etc)
  - [ ] Structure check (keys, required, excluded)
  - [ ] Slicing
  - [ ] micro-CLI for validations
- [ ] Storage
